#!/bin/bash

#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
# https://stackoverflow.com/questions/52749662/using-deprecated-numpy-api
# https://numpy.org/devdocs/f2py/signature-file.html#extensions

rm mkhurrell.*.so
rm mkhurrell.so
rm sgnFile.pyf
f2py --overwrite-signature -m mkhurrell -h sgnFile.pyf mkhurrell_sub.f
f2py -c --fcompiler="gnu95" sgnFile.pyf mkhurrell_sub.f
