#!/bin/bash

#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
# https://stackoverflow.com/questions/52749662/using-deprecated-numpy-api
# https://numpy.org/devdocs/f2py/signature-file.html#extensions

rm pcmdiAmipBcs.*.so
rm pcmdiAmipBcs.so
rm sgnFile.pyf
f2py --overwrite-signature -m pcmdiAmipBcs -h sgnFile.pyf pcmdiAmipBcs_sub.f
f2py -c --fcompiler="gnu95" sgnFile.pyf pcmdiAmipBcs_sub.f
